### ISSUE TITLE
did this ever even work?

### ISSUE THREAD

**Issue by wspresto** [tomwayson/esri-karma-tutorial#27]
interested to know if this project ever worked for anyone else

**Comment by tomwayson** [comment]
It definitely worked at one point. I used this technique in a few production apps. 

That said it's quite out of date now, so if you just walk through the steps in the tutorial I would not be surprised if some update to an upstream dependency breaks this tutorial. I have no intention of keeping things up to date.

@gbochenek just used this technique in a [wab-test-example](https://github.com/gbochenek/wab-test-example), so the technique works. Maybe start there if you were trying to get this working.
